services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trabalhoapi
    ports:
      - "3307:3306"

  api:
    build: .
    container_name: TrabalhoApi
    restart: always
    ports:
      - "5101:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=db;database=trabalhoapi;user=root;password=root
    depends_on:
      - db